<!DOCTYPE html>
<html lang="en"><head>
<script src="apresentação_files/libs/clipboard/clipboard.min.js"></script>
<script src="apresentação_files/libs/quarto-html/tabby.min.js"></script>
<script src="apresentação_files/libs/quarto-html/popper.min.js"></script>
<script src="apresentação_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="apresentação_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="apresentação_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="apresentação_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <meta name="author" content="Eduarda Da Silva Brito">
  <title>Análise e Previsão de Séries Temporais</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="apresentação_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="apresentação_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="apresentação_files/libs/revealjs/dist/theme/quarto-2c1b5f745a11cfad616ebade4a4a7d24.css">
  <link rel="stylesheet" href="styles.css">
  <link href="apresentação_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="apresentação_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="apresentação_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="apresentação_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Análise e Previsão de Séries Temporais</h1>
  <p class="subtitle">Comércio Varejista e Taxa de Desemprego</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Eduarda Da Silva Brito 
</div>
        <p class="quarto-title-affiliation">
            ANÁLISE DE SÉRIES TEMPORAIS<br>Professor: Pedro M. Almeida
          </p>
    </div>
</div>

</section>
<section id="introdução" class="slide level2">
<h2>Introdução</h2>
<p>As séries temporais permitem analisar a evolução de fenômenos ao longo do tempo, identificar padrões de comportamento e realizar previsões para períodos futuros.</p>
<section id="séries-analisadas" class="caixa">
<h3>Séries analisadas</h3>
<ul>
<li class="fragment">🛒 Índice de Volume de Vendas do Comércio Varejista</li>
<li class="fragment">📉 Taxa de Desemprego</li>
</ul>
</section>
</section>
<section id="aspectos-investigados" class="slide level2 caixa">
<h2>Aspectos investigados</h2>
<ul>
<li class="fragment"><p>Tendência</p></li>
<li class="fragment"><p>Sazonalidade</p></li>
<li class="fragment"><p>Modelagem por Suavização Exponencial (ETS)</p></li>
<li class="fragment"><p>Previsão para os 12 meses subsequentes</p></li>
</ul>
</section>
<section id="objetivo" class="slide level2">
<h2>Objetivo</h2>
<div class="caixa-azul">
<p>Analisar o comportamento temporal das séries, identificar seus principais padrões e selecionar modelos de suavização exponencial (ETS) para a realização de previsões de curto prazo.</p>
</div>
</section>
<section id="metodologia" class="slide level2">
<h2>Metodologia</h2>
<div class="caixa">
<p>A análise foi desenvolvida em etapas, desde o tratamento das bases de dados até a obtenção das previsões.</p>
</div>
<ol type="1">
<li class="fragment">Tratamento e limpeza dos dados</li>
<li class="fragment">Análise exploratória</li>
<li class="fragment">Identificação de tendência e sazonalidade</li>
<li class="fragment">Identificação de outliers via STL</li>
<li class="fragment">Modelagem por suavização exponencial ETS</li>
<li class="fragment">Comparação dos modelos</li>
<li class="fragment">Previsão para os 12 meses subsequentes</li>
<li class="fragment">Diagnóstico dos resíduos</li>
</ol>
</section>
<section id="série-1-comércio-varejista" class="slide level2">
<h2>Série 1: Comércio Varejista</h2>
<div class="metricas"> <div class="metrica"> <div class="valor">315</div> <div class="rotulo">observações mensais</div> </div>

<div class="metrica"> <div class="valor">2000–2026</div> <div class="rotulo">período analisado</div> </div>

<div class="metrica"> <div class="valor">SIDRA/IBGE</div> <div class="rotulo">fonte dos dados</div> </div> </div>
<div class="caixa">
<blockquote>
<p>A série representa o Índice de Volume de Vendas do Comércio Varejista, com frequência mensal e base de referência 2022 = 100, sendo utilizada para analisar a evolução da atividade comercial ao longo do tempo.</p>
</blockquote>
</div>
</section>
<section id="estatísticas-descritivas-comércio-varejista" class="slide level2">
<h2>Estatísticas Descritivas – Comércio Varejista</h2>
</section>
<section class="slide level2">

<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Estatística</strong></th>
<th style="text-align: right;"><strong>Valor</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mínimo</td>
<td style="text-align: right;">43,32</td>
</tr>
<tr class="even">
<td style="text-align: left;">1º Quartil</td>
<td style="text-align: right;">60,04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mediana</td>
<td style="text-align: right;">88,92</td>
</tr>
<tr class="even">
<td style="text-align: left;">Média</td>
<td style="text-align: right;">81,78</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3º Quartil</td>
<td style="text-align: right;">97,52</td>
</tr>
<tr class="even">
<td style="text-align: left;">Máximo</td>
<td style="text-align: right;">131,81</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Desvio-padrão</td>
<td style="text-align: right;">22,29</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variância</td>
<td style="text-align: right;">496,85</td>
</tr>
</tbody>
</table>
</section>
<section id="principais-observações" class="slide level2">
<h2>Principais Observações</h2>
<div class="caixa">
<ul>
<li class="fragment">O índice apresentou média de <strong>81,78</strong> pontos e mediana de <strong>88,92</strong> pontos;</li>
<li class="fragment">Os valores variaram entre <strong>43,32</strong> e <strong>131,81</strong> pontos, evidenciando ampla variação ao longo do período analisado;</li>
<li class="fragment">O desvio-padrão de <strong>22,29</strong> pontos indica variabilidade moderada da série.</li>
<li class="fragment">A mediana superior à média sugere leve assimetria na distribuição dos valores.</li>
<li class="fragment">Os quartis indicam que <strong>50% das observações concentraram-se entre 60,04 e 97,52 pontos</strong>.</li>
</ul>
</div>
</section>
<section id="evolução-temporal-do-comércio-varejista" class="slide level2">
<h2>Evolução Temporal do Comércio Varejista</h2>

<img data-src="series_1.png" class="r-stretch"></section>
<section id="principais-observações-1" class="slide level2">
<h2>Principais Observações</h2>
<div class="caixa">
<ul>
<li class="fragment">A série apresenta tendência de crescimento ao longo do período analisado;</li>
<li class="fragment">Observa-se forte sazonalidade, com picos recorrentes no mês de dezembro;</li>
<li class="fragment">Entre 2015 e 2016 verifica-se uma redução temporária do índice, seguida de recuperação gradual;</li>
<li class="fragment">A partir de 2020, observa-se retomada do crescimento, mantendo o padrão sazonal característico da série.</li>
</ul>
</div>
</section>
<section id="sazonalidade-do-comércio-varejista" class="slide level2">
<h2>Sazonalidade do Comércio Varejista</h2>

<img data-src="comercio2.png" style="width:90.0%" class="r-stretch"></section>
<section id="principais-observações-2" class="slide level2">
<h2>Principais Observações</h2>
<div class="caixa">
<ul>
<li class="fragment">A série apresenta um padrão sazonal bem definido, com comportamento semelhante entre os anos;</li>
<li class="fragment">Os menores índices concentram-se, em geral, nos primeiros meses do ano;</li>
<li class="fragment">Os maiores valores são observados sistematicamente no mês de dezembro;</li>
<li class="fragment">O comportamento sazonal está associado ao aumento da atividade comercial no período de compras de final de ano.</li>
</ul>
</div>
</section>
<section id="decomposição-multiplicativa-da-série" class="slide level2">
<h2>Decomposição Multiplicativa da Série</h2>

<img data-src="comercio3.png" style="width:90.0%" class="r-stretch"></section>
<section id="principais-observações-da-decomposição" class="slide level2">
<h2>Principais Observações da Decomposição</h2>
<section id="componentes-da-série" class="caixa">
<h3>Componentes da Série</h3>
<ul>
<li class="fragment"><p>A componente de tendência apresenta crescimento ao longo da maior parte da série;</p></li>
<li class="fragment"><p>Entre <strong>2015 e 2017</strong>, observa-se uma redução temporária, seguida de recuperação gradual;</p></li>
<li class="fragment"><p>A componente sazonal permanece estável, confirmando um padrão de repetição anual.</p></li>
<li class="fragment"><p>Os resíduos permanecem próximos de <strong>1</strong> durante grande parte do período, indicando que a decomposição representa adequadamente a estrutura da série.</p></li>
</ul>
</section>
</section>
<section id="função-de-autocorrelação-acf" class="slide level2">
<h2>Função de Autocorrelação (ACF)</h2>

<img data-src="comercio4.0.png" style="width:90.0%" class="r-stretch"></section>
<section id="principais-observações-da-acf" class="slide level2">
<h2>Principais Observações da ACF</h2>
<div class="caixa">
<ul>
<li class="fragment">As autocorrelações permanecem positivas e elevadas ao longo das defasagens;</li>
<li class="fragment">O decaimento lento das autocorrelações indica a presença de tendência na série;</li>
<li class="fragment">Observa-se um pico na defasagem de <strong>12 meses</strong>, evidenciando sazonalidade anual;</li>
<li class="fragment">As autocorrelações significativas confirmam forte dependência temporal entre as observações.</li>
</ul>
</div>
</section>
<section id="identificação-de-outliers-via-stl" class="slide level2">
<h2>Identificação de Outliers via STL</h2>

<img data-src="comercio5.png" style="width:90.0%" class="r-stretch"></section>
<section id="principais-observações-dos-outliers" class="slide level2">
<h2>Principais Observações dos Outliers</h2>
<div class="caixa">
<ul>
<li class="fragment">A decomposição STL permitiu identificar observações atípicas na série;</li>
<li class="fragment">A maior parte dos resíduos permaneceu próxima do comportamento esperado, indicando estabilidade da série;</li>
<li class="fragment">Os valores atípicos representam desvios pontuais em relação ao padrão temporal da série;</li>
<li class="fragment">Foram detectados <strong>25 resíduos extremos</strong> pelo critério de <strong>3 × IQR</strong>.</li>
</ul>
</div>
</section>
<section id="validação-dos-modelos-ets" class="slide level2">
<h2>Validação dos modelos ETS</h2>
<section id="estratégia-de-validação" class="caixa">
<h4>Estratégia de Validação</h4>
<ul>
<li class="fragment"><p>As séries foram divididas em <strong>conjunto de treinamento</strong> e <strong>conjunto de teste;</strong></p></li>
<li class="fragment"><p>Os <strong>12 meses mais recentes</strong> foram reservados para validação;</p></li>
<li class="fragment"><p>Foram ajustados cinco modelos de suavização exponencial (ETS);</p></li>
<li class="fragment"><p>As previsões foram comparadas com os valores observados no conjunto de teste;</p></li>
<li class="fragment"><p>O modelo de melhor desempenho foi selecionado com base no <strong>menor valor do MAPE.</strong></p></li>
</ul>
</section>
</section>
<section id="comparação-dos-modelos-ets" class="slide level2">
<h2>Comparação dos Modelos ETS</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 51%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Modelo</strong></th>
<th style="text-align: right;"><strong>RMSE</strong></th>
<th style="text-align: right;"><strong>MAE</strong></th>
<th style="text-align: right;"><strong>MAPE (%)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SES</td>
<td style="text-align: right;">8,041</td>
<td style="text-align: right;">5,100</td>
<td style="text-align: right;">4,468</td>
</tr>
<tr class="even">
<td style="text-align: left;">Holt</td>
<td style="text-align: right;">7,679</td>
<td style="text-align: right;">5,369</td>
<td style="text-align: right;">4,845</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Holt amortecido</td>
<td style="text-align: right;">7,679</td>
<td style="text-align: right;">5,369</td>
<td style="text-align: right;">4,845</td>
</tr>
<tr class="even">
<td style="text-align: left;">Holt-Winters aditivo (AAA)</td>
<td style="text-align: right;">2,873</td>
<td style="text-align: right;">2,569</td>
<td style="text-align: right;">2,366</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Holt-Winters multiplicativo (MAM)</strong></td>
<td style="text-align: right;"><strong>2,068</strong></td>
<td style="text-align: right;"><strong>1,516</strong></td>
<td style="text-align: right;"><strong>1,392</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="interpretação" class="slide level2">
<h2>Interpretação</h2>
<section id="principais-resultados" class="caixa">
<h4>Principais Resultados</h4>
<ul>
<li class="fragment"><p>Os modelos <strong>Holt-Winters</strong> apresentaram desempenho superior aos modelos <strong>SES</strong>, <strong>Holt</strong> e <strong>Holt amortecido</strong>.</p></li>
<li class="fragment"><p>O modelo <strong>Holt-Winters multiplicativo (MAM)</strong> apresentou os menores valores de <strong>RMSE (2,068)</strong>, <strong>MAE (1,516)</strong> e <strong>MAPE (1,392%)</strong>.</p></li>
<li class="fragment"><p>Como critério de seleção foi adotado o <strong>menor valor de MAPE</strong>, esse modelo foi escolhido para representar a série do comércio varejista.</p></li>
</ul>
</section>
</section>
<section id="validação-do-modelo-holt-winters-multiplicativo" class="slide level2">
<h2>Validação do Modelo Holt-Winters Multiplicativo</h2>

<img data-src="validaçao_1.png" width="602" class="r-stretch"></section>
<section id="interpretação-da-validação" class="slide level2">
<h2>Interpretação da Validação</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Principais Observações</strong></p>
</div>
<div class="callout-content">
<ul>
<li class="fragment">O modelo reproduziu adequadamente a tendência de crescimento e o padrão sazonal da série.</li>
<li class="fragment">As previsões acompanharam de forma satisfatória os valores observados no período de teste.</li>
<li class="fragment">A maior parte dos valores observados permaneceu dentro dos intervalos de previsão.</li>
<li class="fragment">Esses resultados corroboram as medidas de acurácia obtidas, justificando a escolha do modelo Holt-Winters multiplicativo para a geração das previsões.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="previsão-para-os-próximos-12-meses" class="slide level2">
<h2>Previsão para os Próximos 12 Meses</h2>

<img data-src="comercio6.png" class="quarto-figure quarto-figure-center r-stretch" style="width:85.0%"></section>
<section id="principais-resultados-da-previsão" class="slide level2">
<h2>Principais Resultados da Previsão</h2>
<div class="caixa">
<ul>
<li class="fragment"><p>O modelo prevê a <strong>manutenção da tendência de crescimento</strong> observada na série;</p></li>
<li class="fragment"><p>As previsões preservam o <strong>padrão sazonal</strong> característico do comércio varejista;</p></li>
<li class="fragment"><p>Os maiores valores permanecem concentrados <strong>nos meses finais do ano</strong>, especialmente em dezembro;</p></li>
<li class="fragment"><p>Os intervalos de previsão tornam-se mais amplos ao longo do horizonte de previsão, refletindo o aumento da incerteza das projeções.</p></li>
</ul>
</div>
</section>
<section id="diagnóstico-dos-resíduos" class="slide level2">
<h2>Diagnóstico dos Resíduos</h2>

<img data-src="comercio7.png" class="quarto-figure quarto-figure-center r-stretch" style="width:85.0%"></section>
<section id="principais-resultados-dos-resíduos" class="slide level2">
<h2>Principais Resultados dos Resíduos</h2>
<div class="caixa">
<ul>
<li class="fragment"><p>Os resíduos permanecem centrados em torno de zero ao longo do período analisado;</p></li>
<li class="fragment"><p>Não foram observados padrões sistemáticos evidentes nos resíduos;</p></li>
<li class="fragment"><p>A função de autocorrelação (ACF) indica a presença de algumas autocorrelações significativas em determinadas defasagens.</p></li>
<li class="fragment"><p>O histograma apresenta distribuição aproximadamente simétrica</p></li>
</ul>
</div>
</section>
<section id="teste-de-ljung-box" class="slide level2">
<h2>Teste de Ljung-Box</h2>
<p>Para complementar a análise gráfica, foi aplicado o <strong>teste de Ljung-Box</strong> aos resíduos, com o objetivo de verificar a existência de autocorrelação residual.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Estatística</strong></th>
<th style="text-align: right;"><strong>Valor</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Estatística (Q^*)</td>
<td style="text-align: right;">46,134</td>
</tr>
<tr class="even">
<td style="text-align: left;">Graus de liberdade</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Valor-p</td>
<td style="text-align: right;">0,004266</td>
</tr>
<tr class="even">
<td style="text-align: left;">Defasagens utilizadas</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Modelo df</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</section>
<section id="interpretação-1" class="slide level2">
<h2>Interpretação</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Resultados</strong></p>
</div>
<div class="callout-content">
<ul>
<li class="fragment">O valor-p (<strong>0,004266</strong>) é inferior ao nível de significância de <strong>5%</strong>.</li>
<li class="fragment">Assim, rejeita-se a hipótese de ausência de autocorrelação nos resíduos.</li>
<li class="fragment">Esse resultado indica que ainda existem dependências temporais não completamente capturadas pelo modelo.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="conclusões---comércio-varejista" class="slide level2">
<h2>Conclusões - Comércio Varejista</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<ul>
<li class="fragment"><p>A série apresentou <strong>tendência de crescimento</strong> ao longo do período analisado;</p></li>
<li class="fragment"><p>Foi identificada <strong>forte sazonalidade anual</strong>, com maiores valores concentrados no final do ano;</p></li>
<li class="fragment"><p>A decomposição confirmou a presença de componentes de tendência e sazonalidade bem definidos;</p></li>
<li class="fragment"><p>O modelo <strong>Holt-Winters multiplicativo (ETS(M,A,M))</strong> apresentou o melhor desempenho preditivo, com <strong>MAPE de 1,392%</strong>;</p></li>
<li class="fragment"><p>As previsões indicam a manutenção da tendência de crescimento e do padrão sazonal da série;</p></li>
<li class="fragment"><p>O diagnóstico dos resíduos evidenciou <strong>bom ajuste do modelo</strong>, embora ainda existam indícios de autocorrelação residual.</p></li>
</ul>
</div>
</div>
</div>
</section>
<section id="série-2-taxa-de-desemprego" class="slide level2">
<h2>Série 2: Taxa de Desemprego</h2>
<div class="metricas">
  <div class="metrica">
    <div class="valor">170</div>
    <div class="rotulo">observações mensais</div>
  </div>

  <div class="metrica">
    <div class="valor">2012-2026</div>
    <div class="rotulo">período analisado</div>
  </div>

  <div class="metrica">
    <div class="valor">IPEADATA/IBGE</div>
    <div class="rotulo">fonte dos dados</div>
  </div>
</div>
<div class="caixa">
<p>A série representa a Taxa de Desemprego da população brasileira, medida em percentual e obtida a partir da PNAD Contínua, sendo utilizada para analisar a evolução do mercado de trabalho ao longo do período estudado.</p>
</div>
</section>
<section id="estatísticas-descritivas-taxa-de-desemprego" class="slide level2">
<h2>Estatísticas Descritivas – Taxa de Desemprego</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Estatística</strong></th>
<th style="text-align: right;"><strong>Valor</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mínimo</td>
<td style="text-align: right;">5,10</td>
</tr>
<tr class="even">
<td style="text-align: left;">1º Quartil</td>
<td style="text-align: right;">7,13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mediana</td>
<td style="text-align: right;">8,80</td>
</tr>
<tr class="even">
<td style="text-align: left;">Média</td>
<td style="text-align: right;">9,64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3º Quartil</td>
<td style="text-align: right;">12,10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Máximo</td>
<td style="text-align: right;">14,90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Desvio-padrão</td>
<td style="text-align: right;">2,82</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variância</td>
<td style="text-align: right;">7,93</td>
</tr>
</tbody>
</table>
</section>
<section id="principais-observações-4" class="slide level2">
<h2>Principais Observações</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Resultados</strong></p>
</div>
<div class="callout-content">
<ul>
<li class="fragment">A taxa média de desemprego foi de <strong>9,64%</strong> ao longo do período analisado.</li>
<li class="fragment">A mediana (<strong>8,80%</strong>) é inferior à média, sugerindo <strong>leve assimetria à direita</strong> na distribuição dos valores.</li>
<li class="fragment">A taxa variou entre <strong>5,10%</strong> e <strong>14,90%</strong>, evidenciando elevada variabilidade ao longo do período.</li>
<li class="fragment">O desvio-padrão de <strong>2,82</strong> indica variabilidade moderada da série.</li>
<li class="fragment">Os quartis indicam que <strong>50% das observações</strong> concentraram-se entre <strong>7,13%</strong> e <strong>12,10%</strong>.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="evolução-temporal-da-taxa-de-desemprego" class="slide level2">
<h2>Evolução Temporal da Taxa de Desemprego</h2>

<img data-src="desemprego1.png" style="width:85.0%" class="r-stretch"></section>
<section id="principais-observações-5" class="slide level2">
<h2>Principais Observações</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Resultados</strong></p>
</div>
<div class="callout-content">
<ul>
<li class="fragment">A taxa de desemprego apresentou oscilações significativas ao longo do período analisado.</li>
<li class="fragment">Entre <strong>2015 e 2017</strong>, observou-se crescimento expressivo da taxa de desemprego.</li>
<li class="fragment">O maior nível da série foi registrado entre <strong>2020 e 2021</strong>, período marcado pelos impactos econômicos da pandemia de COVID-19.</li>
<li class="fragment">A partir de <strong>2022</strong>, verificou-se trajetória consistente de redução da taxa de desemprego.</li>
<li class="fragment">Nos períodos mais recentes, a série apresentou estabilização em níveis inferiores aos observados durante o pico da crise.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="sazonalidade-da-taxa-de-desemprego" class="slide level2">
<h2>Sazonalidade da Taxa de Desemprego</h2>

<img data-src="desemprego2.png" style="width:90.0%" class="r-stretch"></section>
<section id="principais-observações-6" class="slide level2">
<h2>Principais Observações</h2>
<div class="caixa">
<ul>
<li class="fragment"><p>A série apresenta sazonalidade menos pronunciada quando comparada ao comércio varejista.</p></li>
<li class="fragment"><p>As variações entre os anos são mais expressivas do que as variações entre os meses;</p></li>
<li class="fragment"><p>Não se observa um padrão sazonal fortemente definido ao longo de todo o período;</p></li>
<li class="fragment"><p>A dinâmica da série é influenciada principalmente pela tendência e por choques econômicos;</p></li>
<li class="fragment"><p>Entre <strong>2020 e 2021</strong>, observam-se os maiores níveis de desemprego em praticamente todos os meses.</p></li>
</ul>
</div>
</section>
<section id="decomposição-da-taxa-de-desemprego" class="slide level2">
<h2>Decomposição da Taxa de Desemprego</h2>

<img data-src="desemprego3.png" class="quarto-figure quarto-figure-center r-stretch" style="width:85.0%"></section>
<section id="principais-observações-da-decomposição-1" class="slide level2">
<h2>Principais Observações da Decomposição</h2>
<div class="caixa">
<ul>
<li class="fragment"><p>A componente de tendência evidencia mudanças importantes na taxa de desemprego ao longo do período analisado;</p></li>
<li class="fragment"><p>Entre <strong>2015 e 2017</strong>, observa-se crescimento da tendência, seguido de elevação até o pico registrado em <strong>2021</strong>;</p></li>
<li class="fragment"><p>A partir de <strong>2022</strong>, verifica-se trajetória consistente de redução da taxa de desemprego;</p></li>
<li class="fragment"><p>A componente sazonal permanece relativamente estável ao longo da série, indicando um padrão sazonal recorrente;</p></li>
<li class="fragment"><p>Os resíduos permaneceram próximos de zero durante grande parte do período, com maior variabilidade entre <strong>2020 e 2021</strong>.</p></li>
</ul>
</div>
</section>
<section id="função-de-autocorrelação-acf-da-taxa-de-desemprego" class="slide level2">
<h2>Função de Autocorrelação (ACF) da Taxa de Desemprego</h2>

<img data-src="desemprego4.png" class="quarto-figure quarto-figure-center r-stretch" style="width:85.0%"></section>
<section id="principais-observações-da-acf-1" class="slide level2">
<h2>Principais Observações da ACF</h2>
<div class="caixa">
<ul>
<li class="fragment"><p>As autocorrelações permanecem positivas e elevadas ao longo das defasagens analisadas;</p></li>
<li class="fragment"><p>O decaimento gradual das autocorrelações indica forte dependência temporal entre as observações;</p></li>
<li class="fragment"><p>O comportamento da ACF evidencia a presença de tendência na série;</p></li>
<li class="fragment"><p>Não são observados picos sazonais tão pronunciados quanto os verificados na série do comércio varejista;</p></li>
<li class="fragment"><p>Esses resultados reforçam a predominância da tendência sobre a sazonalidade na dinâmica da taxa de desemprego.</p></li>
</ul>
</div>
</section>
<section id="identificação-de-outliers-via-stl-1" class="slide level2">
<h2>Identificação de Outliers via STL</h2>

<img data-src="desemprego5.png" style="width:90.0%" class="r-stretch"></section>
<section id="principais-observações-dos-outliers-1" class="slide level2">
<h2>Principais Observações dos Outliers</h2>
<div class="caixa">
<ul>
<li class="fragment"><p>A decomposição STL permitiu identificar observações atípicas na série;</p></li>
<li class="fragment"><p>A maior parte dos resíduos permaneceu próxima do comportamento esperado;</p></li>
<li class="fragment"><p>Os principais desvios concentraram-se entre 2020 e 2021, período associado aos impactos da pandemia de COVID-19;</p></li>
<li class="fragment"><p>Os eventos observados representam choques temporários, sem alterar a estrutura geral da série.</p></li>
</ul>
</div>
</section>
<section id="validação-dos-modelos-ets-1" class="slide level2">
<h2>Validação dos modelos ETS</h2>
<section id="estratégia-de-validação-1" class="caixa">
<h4>Estratégia de Validação</h4>
<ul>
<li class="fragment"><p>A série foi dividida em <strong>conjunto de treinamento</strong> e <strong>conjunto de teste</strong>;</p></li>
<li class="fragment"><p>Os <strong>12 meses mais recentes</strong> foram reservados para validação;</p></li>
<li class="fragment"><p>Foram ajustados cinco modelos de suavização exponencial (ETS);</p></li>
<li class="fragment"><p>As previsões foram comparadas com os valores observados no conjunto de teste;</p></li>
<li class="fragment"><p>O modelo de melhor desempenho foi selecionado com base no <strong>menor valor do MAPE</strong>.</p></li>
</ul>
</section>
</section>
<section id="comparação-dos-modelos-ets-1" class="slide level2">
<h2>Comparação dos Modelos ETS</h2>
<p>Foram comparados cinco modelos de suavização exponencial (ETS) utilizando o conjunto de teste, adotando-se como critério de seleção o menor valor do MAPE</p>
<table class="caption-top">
<colgroup>
<col style="width: 49%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Modelo</strong></th>
<th style="text-align: right;"><strong>RMSE</strong></th>
<th style="text-align: right;"><strong>MAE</strong></th>
<th style="text-align: right;"><strong>MAPE (%)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SES</td>
<td style="text-align: right;">1,017</td>
<td style="text-align: right;">0,967</td>
<td style="text-align: right;">17,532</td>
</tr>
<tr class="even">
<td style="text-align: left;">Holt</td>
<td style="text-align: right;">0,383</td>
<td style="text-align: right;">0,285</td>
<td style="text-align: right;">4,965</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Holt amortecido</td>
<td style="text-align: right;">0,383</td>
<td style="text-align: right;">0,285</td>
<td style="text-align: right;">4,965</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Holt-Winters aditivo (AAA)</strong></td>
<td style="text-align: right;"><strong>0,239</strong></td>
<td style="text-align: right;"><strong>0,212</strong></td>
<td style="text-align: right;"><strong>3,741</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Holt-Winters multiplicativo (MAM)</td>
<td style="text-align: right;">0,412</td>
<td style="text-align: right;">0,369</td>
<td style="text-align: right;">6,696</td>
</tr>
</tbody>
</table>
</section>
<section id="principais-resultados-1" class="slide level2">
<h2>Principais Resultados</h2>
<div class="caixa">
<ul>
<li class="fragment"><p>Os modelos <strong>Holt</strong>, <strong>Holt amortecido</strong> e <strong>Holt-Winters</strong> apresentaram desempenho superior ao modelo <strong>SES</strong>;</p></li>
<li class="fragment"><p>O modelo <strong>Holt-Winters aditivo (AAA</strong>) apresentou os menores valores de <strong>RMSE (0,239)</strong>, <strong>MAE (0,212)</strong> e <strong>MAPE (3,741%)</strong>;</p></li>
<li class="fragment"><p>Como critério de seleção foi adotado o <strong>menor valor de MAPE</strong>, esse modelo foi escolhido para representar a série da <strong>Taxa de Desemprego</strong>.</p></li>
</ul>
</div>
</section>
<section id="validação-do-modelo-holt-winters-aditivo" class="slide level2">
<h2>Validação do Modelo Holt-Winters Aditivo</h2>

<img data-src="avaliação_2.png" class="r-stretch"></section>
<section id="interpretação-2" class="slide level2">
<h2>Interpretação</h2>
<div class="caixa">
<ul>
<li class="fragment"><p>As previsões acompanharam satisfatoriamente o comportamento da taxa de desemprego no conjunto de teste;</p></li>
<li class="fragment"><p>O modelo reproduziu adequadamente a tendência de redução observada ao final da série;</p></li>
<li class="fragment"><p>A maior parte dos valores observados permaneceu próxima das previsões e contida nos respectivos intervalos de previsão;</p></li>
<li class="fragment"><p>Esse resultado é consistente com as medidas de acurácia obtidas, justificando a seleção do modelo Holt-Winters aditivo para a geração das previsões.</p></li>
</ul>
</div>
</section>
<section id="previsão-para-os-próximos-12-meses-1" class="slide level2">
<h2>Previsão para os Próximos 12 Meses</h2>

<img data-src="desemprego7.png" style="width:90.0%" class="r-stretch"></section>
<section id="principais-resultados-da-previsão-1" class="slide level2">
<h2>Principais Resultados da Previsão</h2>
<div class="caixa">
<ul>
<li class="fragment"><p>O modelo projeta a continuidade da tendência de redução da taxa de desemprego ao longo do horizonte de previsão;</p></li>
<li class="fragment"><p>As previsões indicam que a taxa deverá permanecer entre aproximadamente <strong>4,46%</strong> e <strong>5,55%</strong>;</p></li>
<li class="fragment"><p>Observam-se apenas pequenas oscilações sazonais, mantendo níveis relativamente baixos de desemprego;</p></li>
<li class="fragment"><p>Os intervalos de previsão tornam-se gradualmente mais amplos, refletindo o aumento da incerteza das estimativas futuras.</p></li>
</ul>
</div>
</section>
<section id="diagnóstico-dos-resíduos-1" class="slide level2">
<h2>Diagnóstico dos Resíduos</h2>

<img data-src="desemprego8.png" style="width:90.0%" class="r-stretch"></section>
<section id="principais-resultados-dos-resíduos-1" class="slide level2">
<h2>Principais Resultados dos Resíduos</h2>
<div class="caixa">
<ul>
<li class="fragment"><p>Os resíduos permanecem distribuídos em torno de zero durante grande parte do período analisado;</p></li>
<li class="fragment"><p>Observa-se maior variabilidade entre <strong>2020 e 2021</strong>, refletindo as oscilações excepcionais desse período;</p></li>
<li class="fragment"><p>A função de autocorrelação (ACF) indica a presença de algumas autocorrelações significativas em determinadas defasagens;</p></li>
<li class="fragment"><p>O histograma apresenta distribuição aproximadamente simétrica em torno de zero.</p></li>
</ul>
</div>
</section>
<section id="teste-de-ljung-box-1" class="slide level2">
<h2>Teste de Ljung-Box</h2>
<p>Para complementar a análise gráfica, foi aplicado o <strong>teste de Ljung-Box</strong> aos resíduos, com o objetivo de verificar a existência de autocorrelação residual.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Estatística</strong></th>
<th style="text-align: right;"><strong>Valor</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Estatística (Q^*)</td>
<td style="text-align: right;">162,54</td>
</tr>
<tr class="even">
<td style="text-align: left;">Graus de liberdade</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Valor-p</td>
<td style="text-align: right;">&lt; 2,2 × 10<span class="math inline">\(^{-16}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Defasagens utilizadas</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Modelo df</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</section>
<section id="interpretação-3" class="slide level2">
<h2>Interpretação</h2>
<section id="resultados-3" class="caixa-azul">
<h3>Resultados</h3>
<ul>
<li class="fragment">O valor-p (<strong>&lt; 2,2 × 10</strong><span class="math inline">\(^{-16}\)</span>) é inferior ao nível de significância de <strong>5%</strong>.</li>
<li class="fragment">Assim, rejeita-se a hipótese de ausência de autocorrelação nos resíduos.</li>
<li class="fragment">Há evidências estatisticamente significativas de dependência temporal residual.</li>
<li class="fragment">Embora o modelo Holt-Winters aditivo apresente bom desempenho preditivo, ele não capturou completamente toda a estrutura de autocorrelação da série.</li>
</ul>
</section>
</section>
<section id="conclusão---taxa-de-desemprego" class="slide level2">
<h2>Conclusão - Taxa de Desemprego</h2>
<div class="caixa">
<ul>
<li class="fragment"><p>A série apresentou forte influência dos ciclos econômicos ao longo do período analisado;</p></li>
<li class="fragment"><p>O maior nível de desemprego foi observado entre <strong>2020 e 2021</strong>, refletindo os impactos econômicos da pandemia de COVID-19;</p></li>
<li class="fragment"><p>A partir de <strong>2022</strong>, verificou-se trajetória consistente de redução da taxa de desemprego;</p></li>
<li class="fragment"><p>A decomposição e a ACF evidenciaram predominância da tendência e sazonalidade pouco pronunciada;</p></li>
<li class="fragment"><p>O modelo <strong>Holt-Winters aditivo (ETS(A,A,A))</strong> apresentou o melhor desempenho preditivo, com <strong>MAPE de 3,741%</strong>;</p></li>
<li class="fragment"><p>O diagnóstico dos resíduos indicou bom ajuste do modelo, embora ainda existam evidências de autocorrelação residual.</p></li>
</ul>
</div>
</section>
<section id="fontes-dos-dados" class="slide level2">
<h2>Fontes dos Dados</h2>
<div class="caixa">
<ul>
<li class="fragment"><p>IBGE – SIDRA (Tabela 8880)<br>
<br>
https://sidra.ibge.gov.br/tabela/8880</p></li>
<li class="fragment"><p>IPEA – IPEADATA<br>
<br>
https://www.ipeadata.gov.br/</p></li>
</ul>
</div>
</section>
<section id="agradecimentos" class="slide level2">
<h2>Agradecimentos</h2>
<div class="caixa">
<ul>
<li class="fragment">Agradeço a atenção de todos!</li>
</ul>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="apresentação_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="apresentação_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="apresentação_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="apresentação_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="apresentação_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="apresentação_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="apresentação_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="apresentação_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="apresentação_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="apresentação_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>